[theme]
base = "dark"
primaryColor = "#aba6a6ff"         # Soft vintage grey for buttons and accents
backgroundColor = "#000000"      # Deep black background
secondaryBackgroundColor = "#1A1A1A"  # Slightly lighter black for cards/forms
textColor = "#d3d0d0ff"            # Soft white text
font = "serif"                   # Vintage-style font (Georgia, Times)
